# Generated by Django 5.1.7 on 2025-03-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_account_ref_code_kyc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_status",
            field=models.CharField(
                choices=[("active", "Active"), ("in-active", "In-ctive")],
                default="in-active",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="gender",
            field=models.CharField(
                choices=[("female", "Female"), ("male", "Male")], max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="identity_type",
            field=models.CharField(
                choices=[
                    ("national_id_card", "National ID Card"),
                    ("international_passport", "International Passport"),
                    ("driver_licence", "Driver Licence"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("married", "Married"),
                    ("single", "Single"),
                ],
                max_length=40,
            ),
        ),
    ]
